language: node_js
node_js:
  - 0.10
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run preinstall
  - bower install --force
addons:
  code_climate:
    repo_token:
        secure: "d/wFwGhBdJRPTca6FeDees/h/YUP0z4MvQJAxeisyo//+tfhUMEy43hBcdg88LYtS0FQou7oucKK8PDX4BgIhIMPFbDMl1VQ7bRfjWaccI8mH4DvjkJTWL19pUjj3IunZKuWnEHVhHr2Pp7JacgD+S4t4wV/Lh5rw/VY+dE4cmg="
after_script:
  - cat coverage/phantomjs/lcov.info | codeclimate
