language: node_js
node_js:
  - 0.10
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run preinstall
  - bower install --force
addons:
  code_climate:
    repo_token:
    	secure: gMxSeQGfsca/wkH/6vL+1SEQqnNOGSNXBpvgTgXufTCbOjhDdKzQn/6BeaIgJqmByZAfZm0SOtv58N/wEQCSRcZFo0LQuxUCMjaXNi4JPFV5+vaDRYzgT/ENqlL98e10UhCbqCtqHrm7mym1TUj9DBIJo7dQSZ4shdJuIV4wwA4=
after_script:
  - cat coverage/phantomjs/lcov.info | codeclimate
